#!/usr/bin/env bash
# Display "To infinity and beyond" indefinitely and respond to SIGTERM

# Trap SIGTERM and print a message
trap 'echo "I am invincible!!!"' SIGTERM

# Infinite loop
while true; do
    echo "To infinity and beyond"
    sleep 2
done
