#!/usr/bin/env bash
# infinite loop that prints "To infinity and beyond" and handles SIGTERM

# trap SIGTERM and print a message instead of exiting
trap 'echo "I am invincible!!!"' SIGTERM

while true; do
    echo "To infinity and beyond"
    sleep 2
done
